# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helpForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class help_Dialog(object):
    def helpUI(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 267)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.helpGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.helpGridLayout.setContentsMargins(0, 0, 0, 0)
        self.helpGridLayout.setObjectName("helpGridLayout")
        self.outputVerticalLayout = QtWidgets.QVBoxLayout()
        self.outputVerticalLayout.setObjectName("outputVerticalLayout")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.outputVerticalLayout.addWidget(self.textBrowser_3)
        self.helpGridLayout.addLayout(self.outputVerticalLayout, 2, 1, 1, 1)
        self.generationLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.generationLabel.setObjectName("generationLabel")
        self.helpGridLayout.addWidget(self.generationLabel, 1, 0, 1, 1)
        self.inputLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.inputLabel.setObjectName("inputLabel")
        self.helpGridLayout.addWidget(self.inputLabel, 0, 0, 1, 1)
        self.generationVerticalLayout = QtWidgets.QVBoxLayout()
        self.generationVerticalLayout.setObjectName("generationVerticalLayout")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.generationVerticalLayout.addWidget(self.textBrowser_2)
        self.helpGridLayout.addLayout(self.generationVerticalLayout, 1, 1, 1, 1)
        self.inputVerticalLayout = QtWidgets.QVBoxLayout()
        self.inputVerticalLayout.setObjectName("inputVerticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.inputVerticalLayout.addWidget(self.textBrowser)
        self.helpGridLayout.addLayout(self.inputVerticalLayout, 0, 1, 1, 1)
        self.outputLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.outputLabel.setObjectName("outputLabel")
        self.helpGridLayout.addWidget(self.outputLabel, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use the generate song button to generate a MIDI file using the settings in the generation panel, from the MIDI files loaded in the input section.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use the play button to preview your file.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use the save button to open a save dialog in order to save generated songs.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.generationLabel.setText(_translate("Dialog", "Generation"))
        self.inputLabel.setText(_translate("Dialog", "Input"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use the signature length buttons to specify how many patterns will make up a signature.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use the threshold slider to specify a % value that pattern matches will have to exceed the benchmark value by to be considered a pattern. (Default of 20)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use the benchmark slider to specify a % similarity value which patterns will have to meet to be considered in a signature. (Default of 60)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use the pattern length slider to specify how many beats long would would like patterns to be. </p></body></html>"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Use the &quot;load&quot; button to bring up a load dialog, allowing you to load MIDI files into the system. You may preview the audio from files you have loaded using the &quot;play&quot; button.</span></p></body></html>"))
        self.outputLabel.setText(_translate("Dialog", "Output"))
