# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warningUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Warning(object):
    def warnUi(self, Warning):
        self.button_pushed = QtCore.pyqtSignal(int)
        self.choice = 2
        Warning.setObjectName("Warning")
        Warning.resize(396, 252)
        self.centralwidget = QtWidgets.QWidget(Warning)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 364, 162))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.warnLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.warnLabel.setFont(font)
        self.warnLabel.setObjectName("warnLabel")
        self.gridLayout.addWidget(self.warnLabel, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(10, 180, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(300, 180, 75, 23))
        self.playButton.setObjectName("playButton")
        Warning.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Warning)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 396, 22))
        self.menubar.setObjectName("menubar")
        Warning.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Warning)
        self.statusbar.setObjectName("statusbar")
        Warning.setStatusBar(self.statusbar)

        self.retranslateUi(Warning)
        QtCore.QMetaObject.connectSlotsByName(Warning)

    def retranslateUi(self, Warning):
        _translate = QtCore.QCoreApplication.translate
        Warning.setWindowTitle(_translate("Warning", "Warning!"))
        self.warnLabel.setText(_translate("Warning", "Warning!"))
        self.textBrowser.setHtml(_translate("Warning", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Once a file is being played, you won\'t be able to interact with the application until the song being played is complete. If you want to continue with play please click Play, otherwise click Cancel to return to the application. </p></body></html>"))
        self.cancelButton.setText(_translate("Warning", "Cancel"))
        self.playButton.setText(_translate("Warning", "Play"))

        self.playButton.clicked.connect(self.play)
        self.cancelButton.clicked.connect(self.cancel)

    def play(self, Warning):
        Warning.close()

    def cancel(self, Warning):
        Warning.close()